{% set name = "pywin32" %}
{% set version = "223" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mhammond/{{ name }}/archive/b{{ version }}.tar.gz
  sha256: c8be831cb0fc11badf27b6edc0da08984322452e5c98ac84aa158cc89f6d0837
  patches:
  - 0001-scintilla_makefiles.patch
  # - 0002-ucrt-compatibility-fixes.patch
  # - 0003-ucrt-compatibility-fixes-shell.patch
  # disabled - 222 appears to use .i files (swig?) and not cpp files directly anymore.
  # - 0004-fix-mapi-compile-errors.patch
  # - 0005-remove-JOB_OBJECT_RESERVED_LIMIT_VALID_FLAGS.patch
  - ignore_exchange_plugin.patch   # [win64]
  # running the post-install script fails, because we're not installing to the root system.
  #    Just skip it - it's stuff like registering COM stuff that we don't handle anyway.
  - nuke_post_install.patch
  - remove-horrible-PATH-hack-from-pth-file.patch

build:
  number: 1
  script:
    - "{{ PYTHON }} setup.py install --record=record.txt"  # [not py3k]
    - "{{ PYTHON }} setup3.py install --record=record.txt"  # [py3k]
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%

  skip: True  # [not win]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF
  summary: Python extensions for Windows

extra:
  recipe-maintainers:
    - nicoddemus
    - carlodri
