{% set version = "308" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: fe7e2dea1d48a93d6872c841d5a0594faf7401b811fb659d5e3661d7c9b45745
  patches:
    - 0003-remove-PATH-pth-hack.patch
    - do-not-build-scintilla.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}         # [win and python_impl != 'pypy']
    - {{ stdlib("c") }}           # [win and python_impl != 'pypy']
    - {{ compiler("cxx") }}       # [win and python_impl != 'pypy']
  host:
    - python
    - pip                         # [win and python_impl != 'pypy']
  run:
    - python

test:
  requires:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
    - xhochy
