{% set version = "225" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: ec164d85a563189725ecaadba735f6fc207e4b47213d20923c149f001a6bc102
  patches:
    - disable_exchange_modules.patch

build:
  number: 0
  script:
    - "{{ PYTHON }} setup.py -q install --record=record.txt"
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%
  skip: True  # [not win or py27]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF
  summary: Python extensions for Windows

extra:
  recipe-maintainers:
    - nicoddemus
    - carlodri
