{% set version = "306" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: 16e5ad3efbbf997080f67c3010bd4eb0067d499bbade9be1b240b7e85325c167
  patches:
    - 0003-remove-PATH-pth-hack.patch
    - do-not-build-scintilla.patch

build:
  number: 2

requirements:
  build:
    - {{ compiler("c") }}         # [win and python_impl != 'pypy']
    - {{ compiler("cxx") }}       # [win and python_impl != 'pypy']
  host:
    - python
    - pip                         # [win and python_impl != 'pypy']
  run:
    - python

test:
  requires:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
    - xhochy
