{% set version = "306" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: 16e5ad3efbbf997080f67c3010bd4eb0067d499bbade9be1b240b7e85325c167
  patches:
    - 0003-remove-PATH-pth-hack.patch
    - do-not-build-scintilla.patch

build:
  number: 0
  script:
    - |                                                                                           # [win and python_impl != 'pypy']
      @echo on                                                                                    # [win and python_impl != 'pypy']
      set "STDLIB_DIR=%PREFIX%\Lib;%PREFIX%;%LIBRARY_BIN%"                                        # [win and python_impl != 'pypy']
      {{ PYTHON }} setup.py -q install --record=record.txt --skip-verstamp                        # [win and python_impl != 'pypy']
      echo "sleeping for 15"                                                                      # [win and python_impl != 'pypy']
      {{ PYTHON }} -c "import time; time.sleep(15)"                                               # [win and python_impl != 'pypy']
      echo "Copying over stray DLLS"                                                              # [win and python_impl != 'pypy']
      if %ERRORLEVEL% neq 0 exit 1                                                                # [win and python_impl != 'pypy']
      dir %PREFIX%\Lib\site-packages\win32\py*.dll                                                # [win and python_impl != 'pypy']
      copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %PREFIX%\Lib\site-packages\win32\    # [win and python_impl != 'pypy']
      dir %PREFIX%\Lib\site-packages\win32\py*.dll                                                # [win and python_impl != 'pypy']
      if %ERRORLEVEL% neq 0 exit 1                                                                # [win and python_impl != 'pypy']
      dir %LIBRARY_BIN%\py*.dll                                                                   # [win and python_impl != 'pypy']
      copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%\                       # [win and python_impl != 'pypy']
      if %ERRORLEVEL% neq 0 exit 1                                                                # [win and python_impl != 'pypy']
      dir %LIBRARY_BIN%\py*.dll                                                                   # [win and python_impl != 'pypy']
      if %ERRORLEVEL% neq 0 exit 1                                                                # [win and python_impl != 'pypy']
    - echo "noop"


requirements:
  build:                          # [win and python_impl != 'pypy']
    - {{ compiler("c") }}         # [win and python_impl != 'pypy']
    - {{ compiler("cxx") }}       # [win and python_impl != 'pypy']
  host:
    - python
    - pip                         # [win and python_impl != 'pypy']
  run:
    - python

test:
  requires:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
