{% set version = "301" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: 5366613c366c66b521a2e79780dcdf347310bd2b75022e424df320760931999c
  patches:
    - patches/disable_exchange_modules.patch
    - patches/0003-remove-PATH-pth-hack.patch
    - patches/remove_bdist_msi_to_support_pypy.patch
    - patches/0001-remove-modules-needing-pythonservice.cpp-for-pypy.patch
    # Remove these after PyPy 7.3.6 release
    - patches/0004-pre-pypy-3.7.6-PyExc_WindowsError.patch

build:
  number: 0
  script:
    # TODO: remove the following line after PyPy 7.3.6
    - copy %RECIPE_DIR%\import.h %PREFIX%\include\   # [python_impl == "pypy"]
    - copy %RECIPE_DIR%\graminit.h %PREFIX%\include\   # [python_impl == "pypy"]
    - {{ PYTHON }} setup.py -q install --record=record.txt --skip-verstamp
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %PREFIX%\Lib\site-packages\win32\
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%\
  skip: true  # [not win or py27]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
