{% set name = "pywin32" %}
{% set version = "227" %}
{% set hash_type = "sha256" %}
{% set hash = "f82946fb29d55a27b3abcd0b527ef2e8da6ea05b01dfcc40bfc14847b7673e8e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.zip
  {{ hash_type }}: {{ hash }}
  patches:
    - 0001-scintilla-makefiles.patch
    # running the post-install script fails, because we're not installing to the root system.
    #    Just skip it - it's stuff like registering COM stuff that we don't handle anyway.
    - 0002-nuke-post-install.patch
    - 0003-remove-PATH-pth-hack.patch
    - 0004-remove-JOB_OBJECT_RESERVED_LIMIT_VALID_FLAGS.patch

build:
  number: 1
  skip: True  # [not win or py27]

requirements:
  build:
    - {{ compiler('c') }}
    - m2-patch  # [win]
    - m2-gcc-libs  # [win]
    - patch  # [not win]
    # Used to extract MAPI headers at build-time.
    - libarchive  # [win]
  host:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/mhammond/pywin32
  license: PSF
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32
  doc_url: https://pypi.python.org/pypi/pywin32
  doc_source_url: https://sourceforge.net/projects/pywin32/

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
