appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: CMDvkexBHYNAxmpCDcQf1zXncO2mydnbSW0iMgaLYMvGDmSvIXvHU4M7YODR66hg4pnOY2jnO564P6zB5K34Rgmv1k35fuX3olWt/I2ktR8K5HQkQuUqIO74zt3udpYTUzystPqTrvQ1vIhh2Lx2XK05Gb7qVhLIEl+3Zk5QWzpfbCYr3uK8gCUIYyCoW91cxuvFzNcKEGh4KewDJjObwPdZq1gOdwPYyiYUnzEWprI1MIsHYHz5mpQP8aOGCnBbSVVIhagmW93sFC35IL5omLEAyl0mooFsTXLJs3u0HiimmnKvB2wa2oCWMJkpPFQVt8wbaV3i1X2kkfEjsQbuh0dfWXT3w8tQNxOBsEDwsqTPdDn+P5ImQZSFJ/URFyMvpKek/qgBiiHBTsJTb1pdpMkCXBD6eUd6pZ83hfUbxSIht4UxxylWRYgl/GTwvnFiCdIw5x9QHTFsjbI1fab8TVU+PgdmX6D7QquC0eNg4mzQgfhSwqZuRQNT5kdYBUUbXwD/9bZAlEjUtsdfGmK/Yjv/e4B+9I3yAVpenu1zZZlwtIw2Ux9VMexVsxQlAi6nWGvHCrlRcoVqO6cCJNJgmiuzJzJQnWLvrVbpTKv2gQ/u/wGi12HmIwJvwHJIi/lIwlpoCkAn8DVbuhBZVn4jTDOyAQbTsDXxwHOctyABzk0=}
provider:
  win: azure
conda_forge_output_validation: true
